/** Datos invariantes al idioma. */
export const contact = {
  email: 'j.p.armstrong@me.com',
  phone: '+569 7850 5946',
  location: 'Temuco, Chile',
};

export const cv = {
  es: {
    title: 'CV · Juan Pablo Armstrong',
    name: 'Juan Pablo Armstrong',
    tagline: 'Analista Programador · Cloud / AWS',
    downloadPdf: 'Descargar PDF',
    sections: { profile: 'Perfil', project: 'Proyecto Destacado', experience: 'Experiencia', education: 'Formación', skills: 'Habilidades', language: 'Idioma' },
    profile: 'Analista Programador con experiencia en desarrollo web, administración de servidores y diseño de interfaces. Graduate del programa AWS Re/Start 2026, con VecinoClub, plataforma serverless de fidelización en producción. AWS Certified Cloud Practitioner. Autodidacta activo, inglés avanzado (TOEFL 101/120), orientado a resultados concretos.',
    project: {
      title: 'VecinoClub',
      subtitle: 'Plataforma serverless de fidelización para comercios locales de Chile — en producción',
      labels: { backend: 'Backend', frontend: 'Frontend', awsServices: 'Servicios AWS', devops: 'DevOps', landing: 'Landing', architecture: 'Arquitectura' },
      backend: 'FastAPI / Python sobre AWS Lambda',
      frontend: 'React 19 + TypeScript',
      awsServices: 'Lambda · API Gateway · DynamoDB · Cognito · CloudFront · S3 · SES · CloudWatch',
      devops: 'GitHub Actions CI/CD · AWS SAM',
      landing: 'Cloudflare · Vercel',
      architecture: 'Multi-tenant, serverless',
      viewCaseStudy: 'Ver caso de estudio',
      viewPlatform: 'Ver VecinoClub',
    },
    experience: [
      { role: 'Fundador y Desarrollador Full-Stack', company: 'VecinoClub', period: '2026 – Actualidad', location: 'Chile', bullets: ['Diseño, desarrollo, despliegue y operación end-to-end de plataforma SaaS en AWS.', 'Fidelización para comercios locales: los clientes escanean un QR y consultan sellos y puntos sin instalar una app; cada comercio configura beneficios, registra compras y consulta estadísticas.', 'Arquitectura serverless multi-tenant: Lambda, API Gateway, DynamoDB, Cognito, CloudFront, S3 y SES; backend en FastAPI/Python y frontend en React 19 con TypeScript.', 'CI/CD con GitHub Actions y AWS SAM, con gate manual antes de producción.'] },
      { role: 'Cofundador · Desarrollo & Gestión', company: 'Imaquinaria Estudio / Tienda SPA', period: '2016 – Actualidad', location: 'Temuco', bullets: ['Primer comercio y banco de pruebas de VecinoClub.', 'Diseño y desarrollo del programa Bushidō.', 'Gestión de identidad visual, producción de contenido y canales de venta del emprendimiento.'] },
      { role: 'Cofundador · Administrador Web y Editor', company: 'Cuarto Mundo', period: '2014 – 2022', location: 'Chile', bullets: ['Administración y personalización de plataforma WordPress para medio digital de cultura pop.', 'Gestión editorial y producción de contenido desde la fundación.'] },
      { role: 'Administrador de Servidores Web', company: 'Lazos S.A.', period: '2014 – 2015', location: 'Temuco', bullets: ['Administración de servidores e implementación de funcionalidades para clientes.', 'Replicación de navegación e intranet de CONAF para migración interna.'] },
      { role: 'Diseñador UI · Desarrollador Web', company: 'iClub S.A.', period: '2011 – 2012', location: 'Temuco', bullets: ['Diseño de UI para app Android de pedidos en restaurantes.', 'Desarrollo de sitio web corporativo.'] },
    ],
    education: [
      { title: 'AWS Re/Start — Graduate', institution: 'Amazon Web Services', period: '2026', location: 'Temuco, Chile', description: 'Programa intensivo de cloud computing. Badge oficial. AWS Cloud Practitioner en proceso de certificación.' },
      { title: 'Analista Programador', institution: 'Instituto Santo Tomás', period: '2011 – 2015', location: 'Temuco', description: 'Desarrollo de software, bases de datos MySQL, redes y administración de sistemas.' },
      { title: 'Aprende Python Desde Cero', institution: 'Temuco Lab', period: '2025', location: '', description: 'Lógica de programación, sintaxis Python, Google Colab, librería pandas.' },
      { title: 'PrintLab: Innovando en 3D', institution: 'Temuco Lab', period: '2025', location: '', description: 'Modelado en Onshape (cloud), impresión 3D, Cura Slicer.' },
    ],
    skills: [
      { category: 'Cloud / AWS', items: ['Lambda', 'API Gateway', 'DynamoDB', 'Cognito', 'CloudFront', 'S3', 'SES', 'CloudWatch', 'AWS SAM', 'Cloudflare', 'Vercel'] },
      { category: 'Desarrollo', items: ['Python', 'FastAPI', 'React 19', 'TypeScript', 'HTML / CSS', 'MySQL'] },
      { category: 'Plataformas & Herramientas', items: ['WordPress', 'GitHub Actions', 'VS Code', 'Affinity Suite', 'Adobe CC', 'Docker'] },
      { category: 'IA & Agentes de Código', items: ['Claude Code', 'OpenAI Codex', 'Zed', 'herdr'] },
    ],
    language: { title: 'Inglés', level: 'Avanzado — TOEFL 101/120 (2013)', badge: 'C1' },
  },
  en: {
    title: 'CV · Juan Pablo Armstrong',
    name: 'Juan Pablo Armstrong',
    tagline: 'Systems Analyst · Cloud / AWS',
    downloadPdf: 'Download PDF',
    sections: { profile: 'Profile', project: 'Featured Project', experience: 'Experience', education: 'Education', skills: 'Skills', language: 'Language' },
    profile: 'Systems Analyst with experience in web development, server administration, and UI design. Graduate of the AWS Re/Start 2026 program, with VecinoClub, a serverless loyalty platform in production. AWS Certified Cloud Practitioner. Active self-learner, advanced English (TOEFL 101/120), results-oriented.',
    project: {
      title: 'VecinoClub',
      subtitle: 'Serverless loyalty platform for local businesses in Chile — in production',
      labels: { backend: 'Backend', frontend: 'Frontend', awsServices: 'AWS Services', devops: 'DevOps', landing: 'Landing', architecture: 'Architecture' },
      backend: 'FastAPI / Python on AWS Lambda',
      frontend: 'React 19 + TypeScript',
      awsServices: 'Lambda · API Gateway · DynamoDB · Cognito · CloudFront · S3 · SES · CloudWatch',
      devops: 'GitHub Actions CI/CD · AWS SAM',
      landing: 'Cloudflare · Vercel',
      architecture: 'Multi-tenant, serverless',
      viewCaseStudy: 'View case study',
      viewPlatform: 'View VecinoClub',
    },
    experience: [
      { role: 'Founder & Full-Stack Developer', company: 'VecinoClub', period: '2026 – Present', location: 'Chile', bullets: ['End-to-end design, development, deployment, and operation of a SaaS platform on AWS.', 'Loyalty platform for local businesses: customers scan a QR code to check stamps and points without installing an app; each business sets benefits, records purchases, and views statistics.', 'Multi-tenant serverless architecture: Lambda, API Gateway, DynamoDB, Cognito, CloudFront, S3, and SES; backend in FastAPI/Python and frontend in React 19 with TypeScript.', 'CI/CD with GitHub Actions and AWS SAM, with a manual gate before production.'] },
      { role: 'Co-founder · Development & Operations', company: 'Imaquinaria Estudio / Tienda SPA', period: '2016 – Present', location: 'Temuco', bullets: ['VecinoClub’s first business and proving ground.', 'Design and development of the Bushidō program.', 'Brand identity management, content production, and sales channel oversight.'] },
      { role: 'Co-founder · Web Administrator & Editor', company: 'Cuarto Mundo', period: '2014 – 2022', location: 'Chile', bullets: ['Administration and customization of a WordPress platform for a pop culture digital publication.', 'Editorial management and content production since founding.'] },
      { role: 'Web Server Administrator', company: 'Lazos S.A.', period: '2014 – 2015', location: 'Temuco', bullets: ['Server administration and feature implementation for clients.', 'Replicated CONAF\'s navigation and intranet for an internal migration project.'] },
      { role: 'UI Designer · Web Developer', company: 'iClub S.A.', period: '2011 – 2012', location: 'Temuco', bullets: ['UI design for an Android restaurant ordering app.', 'Corporate website development.'] },
    ],
    education: [
      { title: 'AWS Re/Start — Graduate', institution: 'Amazon Web Services', period: '2026', location: 'Temuco, Chile', description: 'Intensive cloud computing program. Official badge. AWS Certified Cloud Practitioner.' },
      { title: 'Systems Analyst Programmer', institution: 'Instituto Santo Tomás', period: '2011 – 2015', location: 'Temuco', description: 'Software development, MySQL databases, networking, and systems administration.' },
      { title: 'Learn Python From Scratch', institution: 'Temuco Lab', period: '2025', location: '', description: 'Programming logic, Python syntax, Google Colab, pandas library.' },
      { title: 'PrintLab: Innovating in 3D', institution: 'Temuco Lab', period: '2025', location: '', description: 'Cloud-based modeling in Onshape, 3D printing, Cura Slicer.' },
    ],
    skills: [
      { category: 'Cloud / AWS', items: ['Lambda', 'API Gateway', 'DynamoDB', 'Cognito', 'CloudFront', 'S3', 'SES', 'CloudWatch', 'AWS SAM', 'Cloudflare', 'Vercel'] },
      { category: 'Development', items: ['Python', 'FastAPI', 'React 19', 'TypeScript', 'HTML / CSS', 'MySQL'] },
      { category: 'Platforms & Tools', items: ['WordPress', 'GitHub Actions', 'VS Code', 'Affinity Suite', 'Adobe CC', 'Docker'] },
      { category: 'AI & Code Agents', items: ['Claude Code', 'OpenAI Codex', 'Zed', 'herdr'] },
    ],
    language: { title: 'English', level: 'Advanced — TOEFL 101/120 (2013)', badge: 'C1' },
  },
};
